repos:
  - repo: https://github.com/nicklockwood/SwiftFormat
    rev: 0.58.7
    hooks:
      - id: swiftformat
        args: [--config, .swiftformat]

  - repo: https://github.com/realm/SwiftLint
    rev: 0.62.2
    hooks:
      - id: swiftlint
        args: [--strict, --config, .swiftlint.yml]
